[AIFlow][frontend] Add Chinese - Simplified
flink-extended/ai-flow pull request #209
Opened 2021-12-09 05:21 UTC by gzhu2

## What is the purpose of the change

*(For example: This pull request makes user can stop workflow externally.)*

## Brief change log

*(for example:)*
  - *Send StopDagEvent to Airflow scheduler via notification service*
  - *Once received StopDagEvent, Airflow scheduler kills all running dag runs*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests.

2021-12-10 08:50 UTC, jiangxin369 commented
Hi @gzhu2, thanks for your pull request, could you please fulfill the necessary information like `Brief change log` which helps review?

2021-12-10 09:16 UTC, gzhu2 commented
Hi

从汉化画面参与前端开发
可以为国内潜在用户快速展示原型为目的.

Pull request已更新
请查阅.

/zhu

________________________________
From: JiangXin ***@***.***>
Sent: Friday, December 10, 2021 4:50:46 PM
To: flink-extended/ai-flow ***@***.***>
Cc: gzhu2 ***@***.***>; Mention ***@***.***>
Subject: Re: [flink-extended/ai-flow] [AIFlow][frontend] Add Chinese - Simplified (PR #209)


Hi @gzhu2<https://github.com/gzhu2>, thanks for your pull request, could you please fulfill the necessary information like Brief change log which helps review?

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/flink-extended/ai-flow/pull/209#issuecomment-990745004>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AV66QZRVW2XOSNOA6QLBGIDUQG5ONANCNFSM5JVQVQ3A>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-12-13 03:12 UTC, SteNicholas requested changes

2021-12-13 03:12 UTC, SteNicholas commented on ai_flow/frontend/src/locales/lang/zh-CN.js
> +  'layouts.userLayout.title': 'AIFlow是一个开源框架，将大数据和人工智能联系起来.',
```suggestion
  'layouts.userLayout.title': 'AIFlow 是一个将大数据和人工智能连接的开源工作流框架。',
```

2021-12-13 03:12 UTC, SteNicholas commented on ai_flow/frontend/src/locales/lang/zh-CN.js
> +  ...project,
Ditto.

2021-12-17 01:59 UTC, SteNicholas commented
@gzhu2 , any update for this pull request?

2022-01-26 06:28 UTC, closed without merging