[AIFlow] Improve overview.md document.
flink-extended/ai-flow pull request #97
Opened 2021-11-04 11:12 UTC by wuchaochen

## What is the purpose of the change

[AIFlow] Improve overview.md document.

2021-11-04 13:17 UTC, jiangxin369 commented on docs/content/architecture/overview.md
> +2. __AIFlow Server__: AIFlow Server provides meta information management and scheduling services.
I think model center should also be metioned.

2021-11-05 03:10 UTC, SteNicholas requested changes

2021-11-05 03:10 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +Currently, we have implemented an [event-based scheduler](https://github.com/flink-extended/ai-flow/tree/master/lib/airflow) by combining AirFlow and Notification Server.
```suggestion
At present, the default scheduler is the event based scheduling version of Airflow which is implemented with the Notification Service.
```

2021-11-05 03:10 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +Notification Server: It is a service that provides event sending and event notification.
```suggestion
Notification Server: It provides notification service which support the event publishing and subscription.
```

2021-11-08 05:55 UTC, SteNicholas requested changes

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +The figure below shows the principle of AIFlow:
```suggestion
The principle of AIFlow is shown in the figure:
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
>  AI Graph: As shown in the figure below, it consists of AI Node, Data Edge and Control Edge .
```suggestion
AI Graph: As shown in the figure below, the AI Graph is consisted of the AI Node, Data Edge and Control Edge . 
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
>  Translator: It converts the AI Graph into the Workflow that the scheduler can execute.
```suggestion
Translator: It translates the AI Graph to the executable workflow for Scheduler.
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +AIFlow Server provides meta information management and scheduling services.
```suggestion
AIFlow Server supports the Meta Service and Scheduling Service to provide the basic service of the AIFlow.
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +Scheduler: Scheduler is responsible for workflow&job execution and support event-based scheduling.
```suggestion
Scheduler: Scheduler is responsible for the execution of the workflow and job with the event-based scheduling mechanism.
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +Notification Server: It provides notification service which support the event publishing and subscription.
```suggestion
Notification Server: It provides Notification Service that supports the event publishing and subscription.
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
>  1. Dataset: It provides dataset meta-information services, including data address, data format and other information.
All `meta-information` could update to `meta`.

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +Scheduling Service: The Scheduling Service converts the workflow into an object that can be recognized by the scheduler
```suggestion
Scheduling Service: The Scheduling Service converts the workflow translated into the executable workflow recognized by Scheduler and schedules the workflow execution.
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +The traditional scheduler can only schedule batch jobs (when upstream job finished then downstream jobs can run)
```suggestion
The traditional scheduler could only supports the scheduling of the batch jobs(It means that after upstream job finished, downstream jobs could run.)
```

2021-11-08 05:55 UTC, SteNicholas commented on docs/content/architecture/overview.md
> +The scheduler for Scheduler Service docking must support event-based scheduling.
Add the introduction of the event-based scheduling. The users don't understand what the event-based scheduling is.

2021-11-08 07:59 UTC, SteNicholas approved these changes

2021-11-08 08:04 UTC, merged